<Notification>:
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Notifications"
            title_halign : 'center'
            elevation:1
            md_bg_color: 1, 0, 0, 1
            left_action_items: [["arrow-left", lambda x: root.notification_back()]]
        ScrollView:
            MDList:
                id: notification_list
                padding:dp(20)